customItemImageCarousel.title=Custom 360° Bilderkarussell
customItemImageCarousel.description=Fügt ein interaktives 360-Grad Bilderkarussell in die Artikelansicht ein.
cancellationForm.title=Widerrufsformular (Theme)
cancellationForm.description=Widerrufsformular des Themes mit korrekter Antwortadresse und Eingangsbestätigung an den Kunden.
